name: assistant
version: 43.0.0+43
publish_to: 'none'
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.9.0
  async: ^2.11.0
  collection: ^1.18.0
  decimal: ^3.0.1
  provider: ^6.1.1
  path_provider: ^2.1.1
  material_symbols_icons: ^4.2758.0
  window_manager: ^0.3.9
  dynamic_color: ^1.6.9
  url_launcher: ^6.3.0
  app_links: ^6.1.1
  file_selector: ^1.0.3
  local_notifier: ^0.1.5
  flutter_local_notifications: ^17.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.7
flutter:
  uses-material-design: true
  assets:
    - asset/
msix_config:
  display_name: Twinning Assistant
  publisher_display_name: TwinStar
  identity_name: TwinStar.Twinning.Assistant
  logo_path: asset/logo.png
  trim_logo: false
  languages: EN-US
  protocol_activation: twinstar.twinning.assistant
  publisher: CN=TwinStar
  architecture: x64
  build_windows: false
  sign_msix: false
  install_certificate: false
