name: assistant
version: 53.0.0+53
publish_to: 'none'
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  path: ^1.9.0
  async: ^2.11.0
  collection: ^1.18.0
  decimal: ^3.0.2
  provider: ^6.1.1
  path_provider: ^2.1.4
  material_symbols_icons: ^4.2780.0
  window_manager: ^0.4.0
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.0
  app_links: ^6.2.0
  file_selector: ^1.0.3
  local_notifier: ^0.1.6
  flutter_local_notifications: ^17.2.2
  super_drag_and_drop: ^0.8.19
  single_child_two_dimensional_scroll_view : ^0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.7
flutter:
  uses-material-design: true
  assets:
    - asset/
msix_config:
  display_name: Twinning Assistant
  publisher_display_name: TwinStar
  identity_name: TwinStar.Twinning.Assistant
  logo_path: asset/logo.png
  trim_logo: false
  languages: EN-US
  protocol_activation: twinstar.twinning.assistant
  context_menu:
    dll_path: build/windows/x64/forwarder/Release/forwarder.dll
    items:
      - type: "*"
        commands:
          - id: TwinningAssistant
            clsid: 9992EC48-22A5-86FA-EA42-72DA1A53F23D
      - type: "Directory"
        commands:
          - id: TwinningAssistant
            clsid: 9992EC48-22A5-86FA-EA42-72DA1A53F23D
      - type: "Directory\\Background"
        commands:
          - id: TwinningAssistant
            clsid: 9992EC48-22A5-86FA-EA42-72DA1A53F23D
  publisher: CN=TwinStar
  architecture: x64
  build_windows: false
  sign_msix: false
  install_certificate: false
