name: shell_gui
version: 10.0.0+10
publish_to: 'none'
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  async: ^2.9.0
  provider: ^6.0.4
  path_provider: ^2.0.12
  window_manager: ^0.3.0
  dynamic_color: ^1.5.4
  file_picker: ^5.2.7
  local_notifier: ^0.1.5
  flutter_local_notifications: ^13.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  msix: ^3.6.6
flutter:
  uses-material-design: true
flutter_icons:
  image_path: asset/logo.png
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
msix_config:
  identity_name: TwinStar.ToolKit.ShellGUI
  publisher: CN=TwinStar
  display_name: TwinStar ToolKit - Shell GUI
  publisher_display_name: TwinStar
  languages: en-us
  logo_path: asset/logo.png
  trim_logo: false
