name: shell_gui
version: 27.0.0+27
publish_to: 'none'
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  async: ^2.11.0
  provider: ^6.0.5
  path: ^1.8.3
  path_provider: ^2.1.1
  window_manager: ^0.3.6
  dynamic_color: ^1.6.6
  file_picker: ^5.5.0
  local_notifier: ^0.1.5
  flutter_local_notifications: ^15.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.4
flutter:
  uses-material-design: true
  assets:
    - asset/
flutter_icons:
  image_path: asset/logo.png
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
msix_config:
  identity_name: TwinStar.ToolKit.ShellGUI
  publisher: CN=TwinStar
  display_name: TwinStar ToolKit - Shell GUI
  publisher_display_name: TwinStar
  languages: en-us
  logo_path: asset/logo.png
  trim_logo: false
